package store

import (
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"

	_ "github.com/mattn/go-sqlite3"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// InitDB creates or opens the dbFile, applies missing migrations and returns a Queries struct (generated by SQLC)
func InitDB(dbFile string) (*Queries, func(), error) {
	closeFn := func() {}

	db, err := sql.Open("sqlite3", dbFile)
	if err != nil {
		return nil, closeFn, fmt.Errorf("open db: %w", err)
	}
	closeFn = func() {
		_ = db.Close()
	}

	if err := migrate(db, migrationsFS); err != nil {
		return nil, closeFn, fmt.Errorf("migrate db: %w", err)
	}

	return New(db), closeFn, nil
}

func migrate(db *sql.DB, fs embed.FS) error {
	// Create migrations table
	_, err := db.Exec(`create table if not exists schema_migrations (
		version text primary key,
		applied_at DATETIME default current_timestamp
	);`)
	if err != nil {
		return fmt.Errorf("create schema_migrations table: %w", err)
	}

	// Read migration files
	entries, err := fs.ReadDir("migrations")
	if err != nil {
		return fmt.Errorf("read migrations dir: %w", err)
	}

	var migrationFiles []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".sql") {
			migrationFiles = append(migrationFiles, entry.Name())
		}
	}
	sort.Strings(migrationFiles)

	for _, file := range migrationFiles {
		// Check if applied
		var exists int
		err := db.QueryRow("select 1 from schema_migrations where version = ?", file).Scan(&exists)
		if err == nil {
			continue // Already applied
		} else if !errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("check migration status for %s: %w", file, err)
		}

		// Apply migration
		content, err := fs.ReadFile("migrations/" + file)
		if err != nil {
			return fmt.Errorf("read migration %s: %w", file, err)
		}

		slog.Info("Applying migration", "file", file)
		tx, err := db.Begin()
		if err != nil {
			return err
		}

		if _, err := tx.Exec(string(content)); err != nil {
			tx.Rollback()
			return fmt.Errorf("execute migration %s: %w", file, err)
		}

		if _, err := tx.Exec("insert into schema_migrations (version) values (?)", file); err != nil {
			tx.Rollback()
			return fmt.Errorf("record migration %s: %w", file, err)
		}

		if err := tx.Commit(); err != nil {
			return fmt.Errorf("commit migration %s: %w", file, err)
		}
	}

	return nil
}
