// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const deleteCategory = `-- name: DeleteCategory :exec
delete
from category
where id = ?1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteCategoryRule = `-- name: DeleteCategoryRule :exec
delete
from category_rule
where id = ?1
`

func (q *Queries) DeleteCategoryRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryRule, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
delete
from project
where id = ?1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteProjectRule = `-- name: DeleteProjectRule :exec
delete
from project_rule
where id = ?1
`

func (q *Queries) DeleteProjectRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectRule, id)
	return err
}

const insertCategory = `-- name: InsertCategory :one

insert into category (name, color)
values (?1, ?2)
returning id, name, color
`

type InsertCategoryParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

// ---------------------------------------
// Categories
// ---------------------------------------
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, insertCategory, arg.Name, arg.Color)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const insertCategoryRule = `-- name: InsertCategoryRule :one

insert into category_rule (pattern, category_id, is_active)
values (?1, ?2, ?3)
returning id, pattern, category_id, is_active
`

type InsertCategoryRuleParams struct {
	Pattern    string `json:"pattern"`
	CategoryID int64  `json:"category_id"`
	IsActive   bool   `json:"is_active"`
}

// ---------------------------------------
// Category Rules
// ---------------------------------------
func (q *Queries) InsertCategoryRule(ctx context.Context, arg InsertCategoryRuleParams) (CategoryRule, error) {
	row := q.db.QueryRowContext(ctx, insertCategoryRule, arg.Pattern, arg.CategoryID, arg.IsActive)
	var i CategoryRule
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.CategoryID,
		&i.IsActive,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one

insert into project (name, color)
values (?1, ?2)
returning id, name, color
`

type InsertProjectParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

// ---------------------------------------
// Projects
// ---------------------------------------
func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject, arg.Name, arg.Color)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const insertProjectRule = `-- name: InsertProjectRule :one

insert into project_rule (pattern, project_id, is_active)
values (?1, ?2, ?3)
returning id, pattern, project_id, is_active
`

type InsertProjectRuleParams struct {
	Pattern   string `json:"pattern"`
	ProjectID int64  `json:"project_id"`
	IsActive  bool   `json:"is_active"`
}

// ---------------------------------------
// Project Rules
// ---------------------------------------
func (q *Queries) InsertProjectRule(ctx context.Context, arg InsertProjectRuleParams) (ProjectRule, error) {
	row := q.db.QueryRowContext(ctx, insertProjectRule, arg.Pattern, arg.ProjectID, arg.IsActive)
	var i ProjectRule
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.ProjectID,
		&i.IsActive,
	)
	return i, err
}

const insertSpan = `-- name: InsertSpan :one
insert into span(app_name, window_title, start_at, end_at)
values (?1, ?2, ?3, ?4)
returning id, app_name, window_title, start_at, end_at
`

type InsertSpanParams struct {
	AppName     string `json:"app_name"`
	WindowTitle string `json:"window_title"`
	StartAt     int64  `json:"start_at"`
	EndAt       int64  `json:"end_at"`
}

func (q *Queries) InsertSpan(ctx context.Context, arg InsertSpanParams) (Span, error) {
	row := q.db.QueryRowContext(ctx, insertSpan,
		arg.AppName,
		arg.WindowTitle,
		arg.StartAt,
		arg.EndAt,
	)
	var i Span
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.WindowTitle,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const selectCategories = `-- name: SelectCategories :many
select id, name, color
from category
order by id
`

func (q *Queries) SelectCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, selectCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCategoryRules = `-- name: SelectCategoryRules :many
select cr.id, cr.pattern, cr.category_id, cr.is_active, c.name, c.color
from category_rule cr
         join category c on cr.category_id = c.id
order by c.id, cr.id
`

type SelectCategoryRulesRow struct {
	ID         int64  `json:"id"`
	Pattern    string `json:"pattern"`
	CategoryID int64  `json:"category_id"`
	IsActive   bool   `json:"is_active"`
	Name       string `json:"name"`
	Color      string `json:"color"`
}

func (q *Queries) SelectCategoryRules(ctx context.Context) ([]SelectCategoryRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectCategoryRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectCategoryRulesRow
	for rows.Next() {
		var i SelectCategoryRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.CategoryID,
			&i.IsActive,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCategorySpans = `-- name: SelectCategorySpans :many
with rule as ( select id, pattern, category_id, is_active from category_rule where category_rule.id = ?2 )
select id, app_name, window_title, start_at, end_at
from span
where regexp_like(app_name, rule.pattern)
   or regexp_like(window_title, rule.pattern)
limit ?1
`

type SelectCategorySpansParams struct {
	Limit      int64 `json:"limit"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) SelectCategorySpans(ctx context.Context, arg SelectCategorySpansParams) ([]Span, error) {
	rows, err := q.db.QueryContext(ctx, selectCategorySpans, arg.Limit, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.WindowTitle,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLatestSpan = `-- name: SelectLatestSpan :one

select id, app_name, window_title, start_at, end_at
from span
order by start_at desc
limit 1
`

// ---------------------------------------
// Spans
// ---------------------------------------
func (q *Queries) SelectLatestSpan(ctx context.Context) (Span, error) {
	row := q.db.QueryRowContext(ctx, selectLatestSpan)
	var i Span
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.WindowTitle,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const selectProjectRules = `-- name: SelectProjectRules :many
select pr.id, pr.pattern, pr.project_id, pr.is_active, p.name, p.color
from project_rule pr
         join project p on pr.project_id = p.id
order by p.id, pr.id
`

type SelectProjectRulesRow struct {
	ID        int64  `json:"id"`
	Pattern   string `json:"pattern"`
	ProjectID int64  `json:"project_id"`
	IsActive  bool   `json:"is_active"`
	Name      string `json:"name"`
	Color     string `json:"color"`
}

func (q *Queries) SelectProjectRules(ctx context.Context) ([]SelectProjectRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectProjectRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectProjectRulesRow
	for rows.Next() {
		var i SelectProjectRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.ProjectID,
			&i.IsActive,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectProjects = `-- name: SelectProjects :many
select id, name, color
from project
order by id
`

func (q *Queries) SelectProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, selectProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSpans = `-- name: SelectSpans :many
select id, app_name, window_title, start_at, end_at
from span
where start_at > ?1
  and end_at < ?2
`

type SelectSpansParams struct {
	StartAt int64 `json:"start_at"`
	EndAt   int64 `json:"end_at"`
}

func (q *Queries) SelectSpans(ctx context.Context, arg SelectSpansParams) ([]Span, error) {
	rows, err := q.db.QueryContext(ctx, selectSpans, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.WindowTitle,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
update category
set name  = ?1,
    color = ?2
where id = ?3
returning id, name, color
`

type UpdateCategoryParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.Name, arg.Color, arg.ID)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const updateCategoryRule = `-- name: UpdateCategoryRule :one
update category_rule
set pattern     = ?1,
    category_id = ?2,
    is_active   = ?3
where id = ?4
returning id, pattern, category_id, is_active
`

type UpdateCategoryRuleParams struct {
	Pattern    string `json:"pattern"`
	CategoryID int64  `json:"category_id"`
	IsActive   bool   `json:"is_active"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateCategoryRule(ctx context.Context, arg UpdateCategoryRuleParams) (CategoryRule, error) {
	row := q.db.QueryRowContext(ctx, updateCategoryRule,
		arg.Pattern,
		arg.CategoryID,
		arg.IsActive,
		arg.ID,
	)
	var i CategoryRule
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.CategoryID,
		&i.IsActive,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
update project
set name  = ?1,
    color = ?2
where id = ?3
returning id, name, color
`

type UpdateProjectParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Color, arg.ID)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const updateProjectRule = `-- name: UpdateProjectRule :one
update project_rule
set pattern    = ?1,
    project_id = ?2,
    is_active  = ?3
where id = ?4
returning id, pattern, project_id, is_active
`

type UpdateProjectRuleParams struct {
	Pattern   string `json:"pattern"`
	ProjectID int64  `json:"project_id"`
	IsActive  bool   `json:"is_active"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateProjectRule(ctx context.Context, arg UpdateProjectRuleParams) (ProjectRule, error) {
	row := q.db.QueryRowContext(ctx, updateProjectRule,
		arg.Pattern,
		arg.ProjectID,
		arg.IsActive,
		arg.ID,
	)
	var i ProjectRule
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.ProjectID,
		&i.IsActive,
	)
	return i, err
}

const updateSpan = `-- name: UpdateSpan :one
update span
set end_at = ?1
where id = ?2
returning id, app_name, window_title, start_at, end_at
`

type UpdateSpanParams struct {
	EndAt int64 `json:"end_at"`
	ID    int64 `json:"id"`
}

func (q *Queries) UpdateSpan(ctx context.Context, arg UpdateSpanParams) (Span, error) {
	row := q.db.QueryRowContext(ctx, updateSpan, arg.EndAt, arg.ID)
	var i Span
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.WindowTitle,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}
