// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Category struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

type CategoryRule struct {
	ID         int64  `json:"id"`
	Pattern    string `json:"pattern"`
	CategoryID int64  `json:"category_id"`
	IsActive   bool   `json:"is_active"`
}

type Project struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

type ProjectRule struct {
	ID        int64  `json:"id"`
	Pattern   string `json:"pattern"`
	ProjectID int64  `json:"project_id"`
	IsActive  bool   `json:"is_active"`
}

type Span struct {
	ID          int64  `json:"id"`
	AppName     string `json:"app_name"`
	WindowTitle string `json:"window_title"`
	StartAt     int64  `json:"start_at"`
	EndAt       int64  `json:"end_at"`
}
